title: wordsim
description: Guess a word from semantic similarity.
baseurl: ""
url: ""
exclude:
  - game
  - node_modules
  - pipeline
  - pipeline-cache
  - scripts
  - tests
  - Gemfile.lock
  - package-lock.json
  - package.json
  - pyproject.toml
  - README.md
  - CHANGELOG.md
  - THIRD_PARTY_NOTICES.md
  - tsconfig.json
